package Prectise;

public class First {
	
/*
 INNER CLASS  :  CLASS WITH IN UNDER CLASS THAT CALLED INNER CLASS 
 
 CLASS{
  CLASS{
  
  		//INNER CLASS 
  }
 }
 
 
 NESTED CLASS AND INNER CLASS DIFFERENT 
 
 -->> ALL THE NESTED CLASS IS INNER 
 NESTED INCLUDE THE STATIC AND NON-STATIC 
 INNER CLASS ONLY INCLUDE NON-STSTIC CLASS 
 
 
 STATIC CLASS CREATE :
 -->> OUTER CLASS AND SECOND IS INNER CLASS 
 THEN YOU CRETAE OBJECT ONLY FOR INNER CLASS 
 
 OUTER.INNER IO = NEW OUTER.INNER();
 
 
 NON-STATIC CREATE 
 
 -->> OUTER O = NEW OUTER();
 	OUTER.INNER IO = O. NEW INNER();
 	
 	
 	1> MEMBER INNER JOIN :
 		-->>OUTER O1 = NEW OUTER(); 
 	2> LOCAL INNER CLASS
 	
 	3> ANONYMOUS INNER CLASS
 	-->> INNER CLASS IN WITHOUT NAME USE 
 	ONLY ONE OBJECT CREATE 
 	
 
 
 */

}
